version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employeeservice_db
    ports:
      - "3306:3306"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
